# base_config.yaml

aws:
  region: us-east-2
  s3_bucket: mushroomsundays

prefect:
  flow_storage: data/prefect_flows/
  log_level: INFO

logging:
  log_dir: logs/
  log_level: DEBUG

requests:
  headers:
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    content-type: "application/json; charset=utf-8"

draftkings:
  url_template: "https://sportsbook-nash.draftkings.com/sites/US-SB/api/v5/eventgroups/{eventgroup_id}/categories/{category_id}/subcategories/{subcategory_id}?format=json"
  sleep_min: 3
  sleep_max: 10
  eventgroups:
- id: 84240
  name: mlb
  categories:
    - id: 743
      name: batter-props
      subcategories:
        - id: 6606
          name: home-runs
        - id: 12883
          name: first-home-run
        - id: 6719
          name: hits
        - id: 6607
          name: total-bases
        - id: 8025
          name: rbis
        - id: 7979
          name: runs-scored
        - id: 12149
          name: hits-runs-rbis
        - id: 9872
          name: stolen-bases
        - id: 6605
          name: strikeouts
        - id: 11031
          name: singles
        - id: 11032
          name: doubles
        - id: 11033
          name: triples
        - id: 12146
          name: walks
    - id: 1031
      name: pitcher-props
      subcategories:
        - id: 15221
          name: strikeouts-thrown
        - id: 9883
          name: outs-recorded
        - id: 9884
          name: to-record-a-win
        - id: 9886
          name: hits-allowed
        - id: 15220
          name: earned-runs-allowed
        - id: 15219
          name: walks-allowed
- id: 88808
  name: nfl-seasonlong
  categories:
    - id: 782
      name: player-stats
      subcategories:
        - id: 7200
          name: passing-yards
        - id: 14770
          name: passing-tds
        - id: 7276
          name: receiving-yards
        - id: 7239
          name: receiving-tds
        - id: 7694
          name: rushing-tds
        - id: 7277
          name: rushing-yards
    - id: 492
      name: game-lines