# base_config.yaml

requests:
  headers:
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    content-type: "application/json; charset=utf-8"
  sleep_min: 3
  sleep_max: 10

api:
  draftkings:
    